-- MySQL Script generated by MySQL Workbench
-- seg 04 abr 2022 19:17:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base_node_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_node_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_node_db` DEFAULT CHARACTER SET utf8 ;
USE `base_node_db` ;

-- -----------------------------------------------------
-- Table `base_node_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_node_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL,
  `email` VARCHAR(64) NOT NULL,
  `date_birth` DATETIME NULL,
  `session_token` VARCHAR(256) NULL,
  `validation_token` VARCHAR(256) NULL,
  `salt` INT NULL,
  `date_registration` DATETIME NULL DEFAULT now(),
  `deleted` TINYINT NULL,
  `email_valid` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_node_db`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_node_db`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(2000) NULL,
  `date_registration` DATETIME NULL DEFAULT now(),
  `deleted` TINYINT NULL,
  `edited` TINYINT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `base_node_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_node_db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_node_db`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(256) NULL,
  `date_registration` DATETIME NULL DEFAULT now(),
  `edited` TINYINT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `base_node_db`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `base_node_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
